### PR TITLE
Rebuild microk8s home page

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Rebuild microk8s.io based on copy doc 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8027/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page matches [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
- Check design 

## Issue / Card

Fixes [#3259](https://github.com/canonical-web-and-design/web-squad/issues/3259)

### CODE REVIEW

**Comment by SirSamTumless** [comment]
@SirSamTumless to add Alex.

**Comment by meralonso** [comment]
Hey @bethcollins92 this is looking good - I have a few changes.

1. After hero banner, can you put white instead of grey? we'll avoid that white gap between those sections
Screenshot 2020-10-06 at 10 39 19

So basically if you invert the white and grey bg that will also solver the problem with these images as they'll go on white bg

Screenshot 2020-10-06 at 10 42 07

Screenshot 2020-10-06 at 10 41 56

**Comment by anthonydillon** [comment]
> After hero banner, can you put that section on white bg instead of grey? we'll avoid that white gap

You can either update the suru strip gradient from white to grey or change the second strip to white.

**Comment by bethcollins92** [comment]
@meralonso I've inverted the strip backgrounds - ready for another review.

**Comment by meralonso** [comment]
> @meralonso I've inverted the strip backgrounds - ready for another review.

thanks @bethcollins92 everything is looking good but I just have one questions - is this grey selector box made on purpose?
 
Screenshot 2020-10-06 at 14 01 28

**Review by sowasred2012 — APPROVED** [review]
LGTM

**Comment by SirSamTumless** [comment]
> Demo starting at https://microk8s-io-335.demos.haus

Alex, could you LMK if you think this is good to go and give it a marketing +1 if it is?

**Comment by alxchalkias** [comment]
@SirSamTumless two comments: 
- Top menu is still the old one
- Asciinema video is the old one (new link in copydoc) 

Rest LGTM!

**Comment by SirSamTumless** [comment]
@alxchalkias We'll wait on the creation of HA and tutorials page before changing the menu :)

**Review by sowasred2012 — APPROVED** [review]
changes LGTM

**Pull request merged**
