### PR TITLE
Installer v2.2.1 release

### PR DESCRIPTION
**Pull request by joedborg**
cc @evilnick @ktsakalozos

v2.2.1 has been released so point to this.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
LGTM +1

**Comment by joedborg** [comment]
Can someone look at this please?  We need to get this release out.

**Review by sowasred2012 — APPROVED** [review]
LGTM, apologies for the delay!

**Comment by sowasred2012** [comment]
@joedborg this has been deployed, and it's live now.

**Pull request merged**
