### PR TITLE
Discourse docs v4.0.2

### PR DESCRIPTION
**Pull request by jpmartinspt**
## Done

Discourse docs v4.0.2

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8027/
- make sure `/docs` work

### CODE REVIEW

**Review by carkod — DISMISSED** [review]
LGTM. Need rebasing

**Comment by jpmartinspt** [comment]
@carkod issues should be resolve now.

**Review by jkfran — APPROVED** [review]
Very nice!

**Comment by jkfran** [comment]
I am merging this

**Pull request merged**
