### PR TITLE
Update scss for auto tables

### LINKED ISSUE #568: add auto-layout for tables
## Summary

As with the other docs sites, this needs the auto-layout option for tables
See for example https://microk8s.io/docs/addons

image

### PR DESCRIPTION
**Pull request by evilnick**
## Done

Add setting for auto width tables

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8027/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes #568

### CODE REVIEW

**Comment by evilnick** [comment]
image

**Review by lyubomir-popov — APPROVED** [review]
LGTM

**Comment by evilnick** [comment]
@lyubomir-popov Thanks. Can someone merge this? I have no rights to do anything on any of these repos any more

**Comment by sowasred2012** [comment]
@lyubomir-popov I can, I'll update

**Pull request merged**
