### PR TITLE
Add Helm descriptions

### PR DESCRIPTION
**Pull request by qs**
Add docs related to https://github.com/ubuntu/microk8s/pull/882

### CODE REVIEW

**Comment by evilnick** [comment]
I think we'll want to include more extensive notes in these docs at a future date, but these links are good for now. Thanks!

**Comment by evilnick** [comment]
@ktsakalozos let me know when helm3 hits stable so we can merge this

**Comment by anthonydillon** [comment]
@ktsakalozos has helm3 hits stable do @evilnick can merge this?

**Comment by tvansteenburgh** [comment]
> @ktsakalozos has helm3 hits stable do @evilnick can merge this?

Nope, it's coming with 1.18 next week.

**Comment by ktsakalozos** [comment]
We can merge this now, 1.18 is out.

**Comment by ktsakalozos** [comment]
@evilnick this is ready for a second review round. Thanks

**Comment by anthonydillon** [comment]
@ktsakalozos what is the plan with this branch?

**Pull request closed without merging**
