### PR TITLE
Search for docs

### LINKED ISSUE #383: Microk8s docs add search
## Summary

Add search for docs

### PR DESCRIPTION
**Pull request by carkod**
## Done

- Add search for docs
- Update to dart sass

## QA
- Go to https://microk8s-io-384.demos.haus/docs
- Search using the new search box, try a term that yields results e.g. `application`
- You may have next button for pagination, check that it works

## Issue / Card

Fixes #383

### CODE REVIEW

**Comment by albertkol** [comment]
@carkod the first search I made on https://microk8s-io-384.demos.haus/docs works.

The second search I make on https://microk8s-io-384.demos.haus/docs/search?q=application returns 404 no matter what I insert.

Pressing Next returns 404 too, but I think it's the same problem.

**Comment by carkod** [comment]
> @carkod the first search I made on https://microk8s-io-384.demos.haus/docs works.
> 
> The second search I make on https://microk8s-io-384.demos.haus/docs/search?q=application returns 404 no matter what I insert.
> 
> Pressing Next returns 404 too, but I think it's the same problem.

Seems to be working for me...  Can you try hard refreshing before you search? Thanks

Screenshot 2021-03-01 at 09 44 47

**Comment by carkod** [comment]
> @carkod the first search I made on https://microk8s-io-384.demos.haus/docs works.
> 
> The second search I make on https://microk8s-io-384.demos.haus/docs/search?q=application returns 404 no matter what I insert.
> 
> Pressing Next returns 404 too, but I think it's the same problem.

Done. Thanks!

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
