### PR TITLE
Add Contact us

### LINKED ISSUE #281: Add contact-us and thank-you page
Add [contact-us](https://drive.google.com/open?id=1KkLHMrGipY4zgIXreujpyJlLvYUs-iAlP-FtpYrZmWA) and [thank-you](https://drive.google.com/open?id=1zAmRxMVFQhUPv9jBjVHJPnWfJMjiB78dQfY__h4pE7o) pages to the site.

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

Add contact-us and thank-you page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8027/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- copy docs for [contact-us](https://drive.google.com/open?id=1KkLHMrGipY4zgIXreujpyJlLvYUs-iAlP-FtpYrZmWA) and [thank-you](https://drive.google.com/open?id=1zAmRxMVFQhUPv9jBjVHJPnWfJMjiB78dQfY__h4pE7o) pages

### CODE REVIEW

**Comment by anthonydillon** [comment]
Looks like there are a lot of unexpected files committed here.

**Comment by pmahnke** [comment]
@anthonydillon I based it on the other PR, what's the right thing to stop this from being a big commit?

**Comment by anthonydillon** [comment]
Honestly, there are so many system files added here is would probably be quicker to create a new PR and pull over the changes to the templates and styles.

**Comment by pmahnke** [comment]
added to main, closing

**Pull request closed without merging**
