### PR TITLE
update multipass usage

### LINKED ISSUE #170: multipass install flow is inconsistent
Docs for installing on macos (specifically multipass) are inconsistent.  The `multipass` section here tells us to use at least 4g ram / 40g disk, `multipass exec` to install microk8s and configure the network, but nothing about enabling services:

https://microk8s.io/docs/install-alternatives

Compare that to the `macOS` section of the getting started page, which does not tell us to use any minimums, nor exec/shell to install or configure the network, but it does enable services:

https://microk8s.io/#get-started

These should be synchronized so users come out the other side with a recommended environment.

### PR DESCRIPTION
**Pull request by kwmonroe**
This PR adds recommended constraints to the multipass VM and prefixes microk8s commands with `multipass exec` when needed.

Fixes #170

### CODE REVIEW

**Comment by caldav** [comment]
@kwmonroe what about just adding one `multipass shell microk8s-vm` as opposed to prefixing all the commands?

**Comment by caldav** [comment]
@kwmonroe It's not ideal if copyable snippets result in an error, so maybe `microk8s.enable dashboard registry istio [...]` should be changed to `microk8s.enable dashboard registry istio`

**Comment by kwmonroe** [comment]
> should be changed to `microk8s.enable dashboard registry istio`

+1 on copyable snippets shouldn't error.  @ktsakalozos could you recommend a sane set of addons that most people would want enabled here?

**Comment by kwmonroe** [comment]
> @kwmonroe what about just adding one `multipass shell microk8s-vm` as opposed to prefixing all the commands?

Yup, the thought crossed my mind.  But we do the same prefixing in [this set](https://microk8s.io/docs/install-alternatives) of docs, so I thought it better to stay consistent.  Maybe worth changing both to `multipass shell`?

**Comment by caldav** [comment]
> > @kwmonroe what about just adding one `multipass shell microk8s-vm` as opposed to prefixing all the commands?
> 
> Yup, the thought crossed my mind. But we do the same prefixing in [this set](https://microk8s.io/docs/install-alternatives) of docs, so I thought it better to stay consistent. Maybe worth changing both to `multipass shell`?

The docs do mention `multipass shell`, so I would say it's OK if they diverge. The biggest issue on the homepage is that copyable snippets blocks have a fixed size. The prefix would hide the actual command.

**Comment by pmahnke** [comment]
you could make them non-copyable?

**Comment by ktsakalozos** [comment]
I am closing this in favor of https://github.com/canonical-web-and-design/microk8s.io/pull/174

**Pull request closed without merging**
