### PR TITLE
Hide install instructions on page load

### LINKED ISSUE #377: Install instructions visible for a second on page load
Got to https://microk8s.io/ and scroll down to see the install instructions section - the instructions are visible for a split second on page load - they should be hidden.

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Fix bug install instructions visible for a second on page load

## QA

- View page at: https://microk8s-io-379.demos.haus
- Comapre to https://microk8s.io/ where on refresh install instructions are visible for a second.
- Check toggling JS on and off, instructions should be visible with JS disabled and not visible until selected when JS is endabled

## Issue / Card

Fixes #377

### CODE REVIEW

**Comment by anthonydillon** [comment]
Please don't do, this. The hide should be applied with JS. So if JS is switched off or there is an error the content is still visible.

**Comment by bethcollins92** [comment]
@anthonydillon ahh ok sure, the `u-hide` class is currently being applied with JS but that's what's causing the content to show for a second on page load, do you have another suggestion on how to stop this from happening as I'm not sure?

**Comment by anthonydillon** [comment]
If that is a concern then a small inline script just below the instructions will execute much quicker.

**Comment by bethcollins92** [comment]
@anthonydillon Ok thanks I've added the script and it's improved the speed. Maybe it's my internet speed but it looked very jumpy to me. (If you don't think it's a concern then I can close the PR without the change)

**Comment by anthonydillon** [comment]
Yeah looks ok to me. I can't think of any other way to provide the
progressive enhancement without some jump.

**Comment by barrymcgee** [comment]
Beth and I discussed this in our pairing session this morning. 

I've taken a look and think this can be simplified and improved by hoisting the check to as early in the browser execution chain as possible.

1. Add a body class of `no-js`
2. Immediately afterwards add a script to remove that class.
3. Add a CSS rule to show the tab content if `no-js` class has not been removed by Javascript and is still present

Screenshot 2021-01-28 at 10 28 01

Screenshot 2021-01-28 at 10 28 38

I have this change in a branch which I can push to this PR if you both agree this is a better way forward.

**Comment by bethcollins92** [comment]
aah, thanks @barrymcgee, this LGTM 👍🏼

**Comment by barrymcgee** [comment]
@bethcollins92 I've force-pushed those changes to this branch.

**Comment by bethcollins92** [comment]
Fixed QA steps - the instructions content should be visible when JS is disabled and only show when selected when JS is enabled.

**Review by anthonydillon — APPROVED** [review]
Looks good thanks :+1:

**Pull request merged**
