### PR TITLE
Convert to flask and add docs

### LINKED ISSUE #270: [Microk8s docs] Convert to Flask

### LINKED ISSUE #271: [Microk8s docs] Replace docs with discourse docs

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Converted the site to flask
- But instead of installing template-finder I just switched the docs to the discourse all in this PR.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8027/
- Check that the site looking the same as the live https://microk8s.io
- Go to docs
- Check they render nicely from https://discourse.ubuntu.com/t/introduction-to-microk8s/15536

## Issue / Card
Resolves #270, Resolves #271

### CODE REVIEW

**Comment by anthonydillon** [comment]
@nottrobin It's still trying to run circleci instead of github actions. Could you take a look in the morning please.

**Comment by anthonydillon** [comment]
@steverydz that will never work. We need to ask the docs team to change the navigation in discourse.

**Comment by anthonydillon** [comment]
@steverydz removed sass-lint, thanks :+1:

**Comment by nottrobin** [comment]
It will keep trying to run circleci until you turn it off in circleci. And you should of course also make it so circleci isn't required in repo settings.

As for actions not running... Aren't you missing a line that tells GH when to run the actions? Something like "on: pull-request"?

**Comment by pmahnke** [comment]
@nottrobin can you help @anthonydillon land this, he is on Swap and someone is chasing.

**Pull request merged**
